import { describe, it, expect, beforeAll } from 'vitest';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const ARTIFACTS = [
  'UiTokens.html',
  'UiPhase2.html',
  'EditorStyles.html',
  'ViewerStyles.html',
  'LibBundle.html',
  'GASAdapter.html',
  'DashboardPhase1.html',
  'DashboardPhase2.html',
  'EditorPage.html',
  'ViewerPage.html',
  'Code.js',
];

describe('build-gas.mjs', () => {
  beforeAll(() => {
    execSync('node scripts/build-gas.mjs', { cwd: ROOT, stdio: 'pipe' });
  });

  it('writes all expected GAS artifacts', () => {
    for (const file of ARTIFACTS) {
      const full = path.join(ROOT, file);
      expect(fs.existsSync(full), `missing ${file}`).toBe(true);
      expect(fs.statSync(full).size).toBeGreaterThan(0);
    }
  });

  it('bundles KnSKLib into LibBundle.html', () => {
    const lib = fs.readFileSync(path.join(ROOT, 'LibBundle.html'), 'utf8');
    expect(lib).toContain('window.KnSKLib');
    expect(lib).toContain('parseCSV');
    expect(lib).toContain('normalizeArchiveReport');
  });

  it('generates Code.js from server modules', () => {
    const code = fs.readFileSync(path.join(ROOT, 'Code.js'), 'utf8');
    expect(code).toContain('AUTO-GENERATED by scripts/build-gas.mjs');
    expect(code).toContain('saveReportToArchive');
    expect(code).toContain('getArchivedReportById');
  });

  it('wraps dashboard scripts in script tags', () => {
    const phase1 = fs.readFileSync(path.join(ROOT, 'DashboardPhase1.html'), 'utf8');
    expect(phase1.startsWith('<script>')).toBe(true);
    expect(phase1.trimEnd().endsWith('</script>')).toBe(true);
  });
});
