#!/usr/bin/env node
/**
 * =============================================================================
 * build-gas.mjs — сборка артефактов для Google Apps Script
 * =============================================================================
 *
 * Запуск: npm run build
 *
 * ЧТО ДЕЛАЕТ:
 *   1. CSS из src/ui/           → UiTokens.html, EditorStyles.html, …
 *   2. JS из src/lib/           → LibBundle.html (общая библиотека KnSKLib)
 *   3. JS из src/dashboard, pages, core → *Page.html, DashboardPhase*.html
 *   4. JS из src/server/        → Code.js (НЕ править Code.js вручную!)
 *
 * После сборки: clasp push → новая версия развёртывания в GAS.
 * =============================================================================
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

function read(rel) {
  return fs.readFileSync(path.join(ROOT, rel), 'utf8');
}

function write(rel, content) {
  const full = path.join(ROOT, rel);
  fs.writeFileSync(full, content, 'utf8');
  console.log('  wrote', rel);
}

/** CSS-файл → HTML-фрагмент для <?!= include('...') ?> */
function wrapStyle(cssPath, outHtml) {
  const css = read(cssPath).trim();
  write(outHtml, `<style>\n${css}\n</style>\n`);
}

/** Один JS-файл → HTML с тегом script */
function wrapScript(jsPath, outHtml) {
  const js = read(jsPath).trim();
  write(outHtml, `<script>\n${js}\n</script>\n`);
}

/** Несколько lib-модулей в один бандл + экспорт window.KnSKLib */
function concatScripts(paths, outHtml, banner) {
  const parts = paths.map((p) => read(p).trim());
  const body = parts.join('\n\n');
  const footer = `
window.KnSKLib = {
  getPlans: typeof getPlans !== 'undefined' ? getPlans : function () { return { year: 220000, weekly: 4583, threshold: 70 }; },
  extractNumber: extractNumber,
  extractFact: extractFact,
  toNum: toNum,
  escapeHtml: escapeHtml,
  sanitizeHtmlFragment: sanitizeHtmlFragment,
  renderHtmlContent: renderHtmlContent,
  parseCSV: parseCSV,
  normalizeArchiveReport: normalizeArchiveReport,
  buildMosFromData: buildMosFromData,
  computeTotals: computeTotals,
  computeTotalsFromMosData: computeTotalsFromMosData,
  computeYearPercent: computeYearPercent,
  computePeriodDeltas: computePeriodDeltas,
};
`;
  write(outHtml, `<script>\n${banner ? banner + '\n' : ''}${body}\n${footer}\n</script>\n`);
}

/** Склейка серверных модулей в корневой Code.js */
function buildCodeJs() {
  const modules = [
    'src/server/webapp.js',
    'src/server/archive.js',
    'src/server/migrations.js',
  ];
  const banner = '// AUTO-GENERATED by scripts/build-gas.mjs — правки в src/server/\n';
  const body = modules.map((p) => read(p).trim()).join('\n\n');
  write('Code.js', banner + body + '\n');
}

console.log('build-gas: styles');
wrapStyle('src/ui/tokens.css', 'UiTokens.html');
wrapStyle('src/ui/phase2.css', 'UiPhase2.html');
wrapStyle('src/ui/editor.css', 'EditorStyles.html');
wrapStyle('src/ui/viewer.css', 'ViewerStyles.html');
wrapStyle('src/ui/kpi-cards.css', 'UiKpiCards.html');

console.log('build-gas: lib bundle');
concatScripts(
  [
    'src/lib/constants.js',
    'src/lib/numbers.js',
    'src/lib/sanitize.js',
    'src/lib/csvParser.js',
    'src/lib/archiveNormalizer.js',
    'src/lib/kpiCalculator.js',
  ],
  'LibBundle.html',
  '/* KnSK shared library */'
);

console.log('build-gas: client modules');
wrapScript('src/core/GoogleAppsScriptAdapter.js', 'GASAdapter.html');
wrapScript('src/dashboard/dashboardPhase1.js', 'DashboardPhase1.html');
wrapScript('src/dashboard/dashboardPhase2.js', 'DashboardPhase2.html');
wrapScript('src/pages/editor.js', 'EditorPage.html');
wrapScript('src/pages/viewer.js', 'ViewerPage.html');

console.log('build-gas: server');
buildCodeJs();

console.log('build-gas: done');
